name: MLflow CI and Docker Build

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'

    # INSTALL MLFLOW
    - name: Install MLflow
      run: |
        pip install mlflow pandas

    # JALANKAN MLFLOW 
    - name: Run MLflow Project (Training Model via Conda)
      run: |
        export MLFLOW_TRACKING_URI="file://$(pwd)/mlruns_fresh"
        mlflow run MLProject/ --experiment-name="Heart_Disease_Classification_Basic"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get MLflow Run ID, Build, & Push
      run: |
        export MLFLOW_TRACKING_URI="file://$(pwd)/mlruns_fresh"
        RUN_ID=$(python -c "import mlflow; runs=mlflow.search_runs(experiment_names=['Heart_Disease_Classification_Basic']); print(runs.iloc[0].run_id)")
        echo "Ditemukan Run ID: $RUN_ID"
        
        # Build Docker Image
        mlflow models build-docker -m "runs:/$RUN_ID/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-model:latest"
        
        # Push ke Docker Hub
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-model:latest"
        
    - name: Commit and push MLflow artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-save MLflow artifacts to repo [skip ci]"
          file_pattern: 'mlruns_fresh/**'